query GetQuestionCollection($id: ID!) {
  questionCollection(id: $id) {
    ...QuestionCollectionItem
    questions {
      ...QuestionItem
      options {
        ...QuestionOptionItem
      }
    }
  }
} 