query PaginateQuestionCollections($paginationInput: PaginationInput) {
  paginatedQuestionCollections(paginationInput: $paginationInput) {
    pagination {
      ...Pagination
    }
    items {
      ...QuestionCollectionItem
    }
  }
} 