extend type Mutation {
  register(input: RegisterInput!): Boolean!
  login(input: LoginInput!): Auth!
  logout: Boolean!
  renewToken(refreshToken: String!): Auth!
}

extend type Query {
  me: User!
  isAuthenticated: Boolean!
}


type Auth {
  accessToken: String!
  refreshToken: String!
}


input LoginInput {
  email: String!
  password: String!
}

input RegisterInput {
  email: String!
  password: String!
}
