extend type Query {
  paginatedUsers(paginationInput: PaginationInput): PaginatedUser!
}
extend type Mutation {
  adminCreateUser(input: AdminCreateUserInput!): User!
  adminEditUser(id: ID!, input: AdminEditUserInput!): User!
}

input AdminCreateUserInput {
  email: String!
  username: String!
  password: String!
}

input AdminEditUserInput {
  email: String
  password: String
  isActive: Boolean
}

type User {
  id: ID!
  email: String!
  username: String!
  firstName: String
  lastName: String
  isActive: Boolean!
  roles: [Role!]!
  permissions: [PermissionEnum!]!
}

type Role {
  id: ID!
  name: String!
}

type PaginatedUser {
  pagination: Pagination!
  items: [User!]!
}
