input PaginationInput {
  page: Int!
  limit: Int!
  search: String
}


type Pagination {
  currentPage: Int!
  totalPages: Int!
  totalItems: Int!
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}
