// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"template/internal/ent/course"
	"template/internal/ent/coursesection"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// CourseSection is the model entity for the CourseSection schema.
type CourseSection struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CourseID holds the value of the "course_id" field.
	CourseID uuid.UUID `json:"course_id,omitempty"`
	// SectionID holds the value of the "section_id" field.
	SectionID *uuid.UUID `json:"section_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Order holds the value of the "order" field.
	Order int `json:"order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CourseSectionQuery when eager-loading is set.
	Edges        CourseSectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CourseSectionEdges holds the relations/edges for other nodes in the graph.
type CourseSectionEdges struct {
	// Course holds the value of the course edge.
	Course *Course `json:"course,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *CourseSection `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*CourseSection `json:"children,omitempty"`
	// CourseSectionVideos holds the value of the course_section_videos edge.
	CourseSectionVideos []*Video `json:"course_section_videos,omitempty"`
	// QuestionCollections holds the value of the question_collections edge.
	QuestionCollections []*QuestionCollection `json:"question_collections,omitempty"`
	// TestSessions holds the value of the test_sessions edge.
	TestSessions []*TestSession `json:"test_sessions,omitempty"`
	// Tests holds the value of the tests edge.
	Tests []*Test `json:"tests,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// CourseOrErr returns the Course value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseSectionEdges) CourseOrErr() (*Course, error) {
	if e.Course != nil {
		return e.Course, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: course.Label}
	}
	return nil, &NotLoadedError{edge: "course"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseSectionEdges) ParentOrErr() (*CourseSection, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: coursesection.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e CourseSectionEdges) ChildrenOrErr() ([]*CourseSection, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// CourseSectionVideosOrErr returns the CourseSectionVideos value or an error if the edge
// was not loaded in eager-loading.
func (e CourseSectionEdges) CourseSectionVideosOrErr() ([]*Video, error) {
	if e.loadedTypes[3] {
		return e.CourseSectionVideos, nil
	}
	return nil, &NotLoadedError{edge: "course_section_videos"}
}

// QuestionCollectionsOrErr returns the QuestionCollections value or an error if the edge
// was not loaded in eager-loading.
func (e CourseSectionEdges) QuestionCollectionsOrErr() ([]*QuestionCollection, error) {
	if e.loadedTypes[4] {
		return e.QuestionCollections, nil
	}
	return nil, &NotLoadedError{edge: "question_collections"}
}

// TestSessionsOrErr returns the TestSessions value or an error if the edge
// was not loaded in eager-loading.
func (e CourseSectionEdges) TestSessionsOrErr() ([]*TestSession, error) {
	if e.loadedTypes[5] {
		return e.TestSessions, nil
	}
	return nil, &NotLoadedError{edge: "test_sessions"}
}

// TestsOrErr returns the Tests value or an error if the edge
// was not loaded in eager-loading.
func (e CourseSectionEdges) TestsOrErr() ([]*Test, error) {
	if e.loadedTypes[6] {
		return e.Tests, nil
	}
	return nil, &NotLoadedError{edge: "tests"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CourseSection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coursesection.FieldSectionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case coursesection.FieldOrder:
			values[i] = new(sql.NullInt64)
		case coursesection.FieldTitle, coursesection.FieldDescription:
			values[i] = new(sql.NullString)
		case coursesection.FieldCreatedAt, coursesection.FieldUpdatedAt, coursesection.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case coursesection.FieldID, coursesection.FieldCourseID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CourseSection fields.
func (cs *CourseSection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coursesection.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cs.ID = *value
			}
		case coursesection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cs.CreatedAt = value.Time
			}
		case coursesection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cs.UpdatedAt = value.Time
			}
		case coursesection.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				cs.DeletedAt = new(time.Time)
				*cs.DeletedAt = value.Time
			}
		case coursesection.FieldCourseID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field course_id", values[i])
			} else if value != nil {
				cs.CourseID = *value
			}
		case coursesection.FieldSectionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field section_id", values[i])
			} else if value.Valid {
				cs.SectionID = new(uuid.UUID)
				*cs.SectionID = *value.S.(*uuid.UUID)
			}
		case coursesection.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				cs.Title = value.String
			}
		case coursesection.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				cs.Description = new(string)
				*cs.Description = value.String
			}
		case coursesection.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				cs.Order = int(value.Int64)
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CourseSection.
// This includes values selected through modifiers, order, etc.
func (cs *CourseSection) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// QueryCourse queries the "course" edge of the CourseSection entity.
func (cs *CourseSection) QueryCourse() *CourseQuery {
	return NewCourseSectionClient(cs.config).QueryCourse(cs)
}

// QueryParent queries the "parent" edge of the CourseSection entity.
func (cs *CourseSection) QueryParent() *CourseSectionQuery {
	return NewCourseSectionClient(cs.config).QueryParent(cs)
}

// QueryChildren queries the "children" edge of the CourseSection entity.
func (cs *CourseSection) QueryChildren() *CourseSectionQuery {
	return NewCourseSectionClient(cs.config).QueryChildren(cs)
}

// QueryCourseSectionVideos queries the "course_section_videos" edge of the CourseSection entity.
func (cs *CourseSection) QueryCourseSectionVideos() *VideoQuery {
	return NewCourseSectionClient(cs.config).QueryCourseSectionVideos(cs)
}

// QueryQuestionCollections queries the "question_collections" edge of the CourseSection entity.
func (cs *CourseSection) QueryQuestionCollections() *QuestionCollectionQuery {
	return NewCourseSectionClient(cs.config).QueryQuestionCollections(cs)
}

// QueryTestSessions queries the "test_sessions" edge of the CourseSection entity.
func (cs *CourseSection) QueryTestSessions() *TestSessionQuery {
	return NewCourseSectionClient(cs.config).QueryTestSessions(cs)
}

// QueryTests queries the "tests" edge of the CourseSection entity.
func (cs *CourseSection) QueryTests() *TestQuery {
	return NewCourseSectionClient(cs.config).QueryTests(cs)
}

// Update returns a builder for updating this CourseSection.
// Note that you need to call CourseSection.Unwrap() before calling this method if this CourseSection
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *CourseSection) Update() *CourseSectionUpdateOne {
	return NewCourseSectionClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the CourseSection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *CourseSection) Unwrap() *CourseSection {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: CourseSection is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *CourseSection) String() string {
	var builder strings.Builder
	builder.WriteString("CourseSection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("created_at=")
	builder.WriteString(cs.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(cs.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := cs.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("course_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.CourseID))
	builder.WriteString(", ")
	if v := cs.SectionID; v != nil {
		builder.WriteString("section_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(cs.Title)
	builder.WriteString(", ")
	if v := cs.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("order=")
	builder.WriteString(fmt.Sprintf("%v", cs.Order))
	builder.WriteByte(')')
	return builder.String()
}

// CourseSections is a parsable slice of CourseSection.
type CourseSections []*CourseSection
