// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"template/internal/ent/media"
	"template/internal/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Media is the model entity for the Media schema.
type Media struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// FileURL holds the value of the "file_url" field.
	FileURL string `json:"file_url,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// UploaderID holds the value of the "uploader_id" field.
	UploaderID uuid.UUID `json:"uploader_id,omitempty"`
	// Additional metadata for the file
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaQuery when eager-loading is set.
	Edges        MediaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaEdges holds the relations/edges for other nodes in the graph.
type MediaEdges struct {
	// UserMedia holds the value of the user_media edge.
	UserMedia []*User `json:"user_media,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// CourseMedia holds the value of the course_media edge.
	CourseMedia []*Course `json:"course_media,omitempty"`
	// VideoMedia holds the value of the video_media edge.
	VideoMedia []*Video `json:"video_media,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserMediaOrErr returns the UserMedia value or an error if the edge
// was not loaded in eager-loading.
func (e MediaEdges) UserMediaOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.UserMedia, nil
	}
	return nil, &NotLoadedError{edge: "user_media"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CourseMediaOrErr returns the CourseMedia value or an error if the edge
// was not loaded in eager-loading.
func (e MediaEdges) CourseMediaOrErr() ([]*Course, error) {
	if e.loadedTypes[2] {
		return e.CourseMedia, nil
	}
	return nil, &NotLoadedError{edge: "course_media"}
}

// VideoMediaOrErr returns the VideoMedia value or an error if the edge
// was not loaded in eager-loading.
func (e MediaEdges) VideoMediaOrErr() ([]*Video, error) {
	if e.loadedTypes[3] {
		return e.VideoMedia, nil
	}
	return nil, &NotLoadedError{edge: "video_media"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Media) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case media.FieldMetadata:
			values[i] = new([]byte)
		case media.FieldFileName, media.FieldFileURL, media.FieldMimeType:
			values[i] = new(sql.NullString)
		case media.FieldCreatedAt, media.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case media.FieldID, media.FieldUploaderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Media fields.
func (m *Media) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case media.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				m.ID = *value
			}
		case media.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				m.CreatedAt = value.Time
			}
		case media.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				m.UpdatedAt = value.Time
			}
		case media.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				m.FileName = value.String
			}
		case media.FieldFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_url", values[i])
			} else if value.Valid {
				m.FileURL = value.String
			}
		case media.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				m.MimeType = value.String
			}
		case media.FieldUploaderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uploader_id", values[i])
			} else if value != nil {
				m.UploaderID = *value
			}
		case media.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Media.
// This includes values selected through modifiers, order, etc.
func (m *Media) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// QueryUserMedia queries the "user_media" edge of the Media entity.
func (m *Media) QueryUserMedia() *UserQuery {
	return NewMediaClient(m.config).QueryUserMedia(m)
}

// QueryUser queries the "user" edge of the Media entity.
func (m *Media) QueryUser() *UserQuery {
	return NewMediaClient(m.config).QueryUser(m)
}

// QueryCourseMedia queries the "course_media" edge of the Media entity.
func (m *Media) QueryCourseMedia() *CourseQuery {
	return NewMediaClient(m.config).QueryCourseMedia(m)
}

// QueryVideoMedia queries the "video_media" edge of the Media entity.
func (m *Media) QueryVideoMedia() *VideoQuery {
	return NewMediaClient(m.config).QueryVideoMedia(m)
}

// Update returns a builder for updating this Media.
// Note that you need to call Media.Unwrap() before calling this method if this Media
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Media) Update() *MediaUpdateOne {
	return NewMediaClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Media entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Media) Unwrap() *Media {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Media is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Media) String() string {
	var builder strings.Builder
	builder.WriteString("Media(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(m.FileName)
	builder.WriteString(", ")
	builder.WriteString("file_url=")
	builder.WriteString(m.FileURL)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("uploader_id=")
	builder.WriteString(fmt.Sprintf("%v", m.UploaderID))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// MediaSlice is a parsable slice of Media.
type MediaSlice []*Media
