// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"template/internal/ent/question"
	"template/internal/ent/questionoption"
	"template/internal/ent/testquestionanswer"
	"template/internal/ent/testsession"
	"template/internal/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TestQuestionAnswer is the model entity for the TestQuestionAnswer schema.
type TestQuestionAnswer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// QuestionID holds the value of the "question_id" field.
	QuestionID uuid.UUID `json:"question_id,omitempty"`
	// SelectedOptionID holds the value of the "selected_option_id" field.
	SelectedOptionID *uuid.UUID `json:"selected_option_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// SelectedOptionText holds the value of the "selected_option_text" field.
	SelectedOptionText *string `json:"selected_option_text,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TestQuestionAnswerQuery when eager-loading is set.
	Edges        TestQuestionAnswerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TestQuestionAnswerEdges holds the relations/edges for other nodes in the graph.
type TestQuestionAnswerEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// SelectedOption holds the value of the selected_option edge.
	SelectedOption *QuestionOption `json:"selected_option,omitempty"`
	// TestSession holds the value of the test_session edge.
	TestSession *TestSession `json:"test_session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestQuestionAnswerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestQuestionAnswerEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// SelectedOptionOrErr returns the SelectedOption value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestQuestionAnswerEdges) SelectedOptionOrErr() (*QuestionOption, error) {
	if e.SelectedOption != nil {
		return e.SelectedOption, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: questionoption.Label}
	}
	return nil, &NotLoadedError{edge: "selected_option"}
}

// TestSessionOrErr returns the TestSession value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestQuestionAnswerEdges) TestSessionOrErr() (*TestSession, error) {
	if e.TestSession != nil {
		return e.TestSession, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: testsession.Label}
	}
	return nil, &NotLoadedError{edge: "test_session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TestQuestionAnswer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case testquestionanswer.FieldSelectedOptionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case testquestionanswer.FieldSelectedOptionText:
			values[i] = new(sql.NullString)
		case testquestionanswer.FieldCreatedAt, testquestionanswer.FieldUpdatedAt, testquestionanswer.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case testquestionanswer.FieldID, testquestionanswer.FieldUserID, testquestionanswer.FieldQuestionID, testquestionanswer.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TestQuestionAnswer fields.
func (tqa *TestQuestionAnswer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case testquestionanswer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tqa.ID = *value
			}
		case testquestionanswer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tqa.CreatedAt = value.Time
			}
		case testquestionanswer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tqa.UpdatedAt = value.Time
			}
		case testquestionanswer.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				tqa.DeletedAt = new(time.Time)
				*tqa.DeletedAt = value.Time
			}
		case testquestionanswer.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				tqa.UserID = *value
			}
		case testquestionanswer.FieldQuestionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field question_id", values[i])
			} else if value != nil {
				tqa.QuestionID = *value
			}
		case testquestionanswer.FieldSelectedOptionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field selected_option_id", values[i])
			} else if value.Valid {
				tqa.SelectedOptionID = new(uuid.UUID)
				*tqa.SelectedOptionID = *value.S.(*uuid.UUID)
			}
		case testquestionanswer.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				tqa.SessionID = *value
			}
		case testquestionanswer.FieldSelectedOptionText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selected_option_text", values[i])
			} else if value.Valid {
				tqa.SelectedOptionText = new(string)
				*tqa.SelectedOptionText = value.String
			}
		default:
			tqa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TestQuestionAnswer.
// This includes values selected through modifiers, order, etc.
func (tqa *TestQuestionAnswer) Value(name string) (ent.Value, error) {
	return tqa.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TestQuestionAnswer entity.
func (tqa *TestQuestionAnswer) QueryUser() *UserQuery {
	return NewTestQuestionAnswerClient(tqa.config).QueryUser(tqa)
}

// QueryQuestion queries the "question" edge of the TestQuestionAnswer entity.
func (tqa *TestQuestionAnswer) QueryQuestion() *QuestionQuery {
	return NewTestQuestionAnswerClient(tqa.config).QueryQuestion(tqa)
}

// QuerySelectedOption queries the "selected_option" edge of the TestQuestionAnswer entity.
func (tqa *TestQuestionAnswer) QuerySelectedOption() *QuestionOptionQuery {
	return NewTestQuestionAnswerClient(tqa.config).QuerySelectedOption(tqa)
}

// QueryTestSession queries the "test_session" edge of the TestQuestionAnswer entity.
func (tqa *TestQuestionAnswer) QueryTestSession() *TestSessionQuery {
	return NewTestQuestionAnswerClient(tqa.config).QueryTestSession(tqa)
}

// Update returns a builder for updating this TestQuestionAnswer.
// Note that you need to call TestQuestionAnswer.Unwrap() before calling this method if this TestQuestionAnswer
// was returned from a transaction, and the transaction was committed or rolled back.
func (tqa *TestQuestionAnswer) Update() *TestQuestionAnswerUpdateOne {
	return NewTestQuestionAnswerClient(tqa.config).UpdateOne(tqa)
}

// Unwrap unwraps the TestQuestionAnswer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tqa *TestQuestionAnswer) Unwrap() *TestQuestionAnswer {
	_tx, ok := tqa.config.driver.(*txDriver)
	if !ok {
		panic("ent: TestQuestionAnswer is not a transactional entity")
	}
	tqa.config.driver = _tx.drv
	return tqa
}

// String implements the fmt.Stringer.
func (tqa *TestQuestionAnswer) String() string {
	var builder strings.Builder
	builder.WriteString("TestQuestionAnswer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tqa.ID))
	builder.WriteString("created_at=")
	builder.WriteString(tqa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tqa.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := tqa.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", tqa.UserID))
	builder.WriteString(", ")
	builder.WriteString("question_id=")
	builder.WriteString(fmt.Sprintf("%v", tqa.QuestionID))
	builder.WriteString(", ")
	if v := tqa.SelectedOptionID; v != nil {
		builder.WriteString("selected_option_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", tqa.SessionID))
	builder.WriteString(", ")
	if v := tqa.SelectedOptionText; v != nil {
		builder.WriteString("selected_option_text=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// TestQuestionAnswers is a parsable slice of TestQuestionAnswer.
type TestQuestionAnswers []*TestQuestionAnswer
