// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"template/internal/ent/question"
	"template/internal/ent/questionoption"
	"template/internal/ent/testsession"
	"template/internal/ent/testsessionanswer"
	"template/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TestSessionAnswerCreate is the builder for creating a TestSessionAnswer entity.
type TestSessionAnswerCreate struct {
	config
	mutation *TestSessionAnswerMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tsac *TestSessionAnswerCreate) SetCreatedAt(t time.Time) *TestSessionAnswerCreate {
	tsac.mutation.SetCreatedAt(t)
	return tsac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tsac *TestSessionAnswerCreate) SetNillableCreatedAt(t *time.Time) *TestSessionAnswerCreate {
	if t != nil {
		tsac.SetCreatedAt(*t)
	}
	return tsac
}

// SetUpdatedAt sets the "updated_at" field.
func (tsac *TestSessionAnswerCreate) SetUpdatedAt(t time.Time) *TestSessionAnswerCreate {
	tsac.mutation.SetUpdatedAt(t)
	return tsac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsac *TestSessionAnswerCreate) SetNillableUpdatedAt(t *time.Time) *TestSessionAnswerCreate {
	if t != nil {
		tsac.SetUpdatedAt(*t)
	}
	return tsac
}

// SetDeletedAt sets the "deleted_at" field.
func (tsac *TestSessionAnswerCreate) SetDeletedAt(t time.Time) *TestSessionAnswerCreate {
	tsac.mutation.SetDeletedAt(t)
	return tsac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tsac *TestSessionAnswerCreate) SetNillableDeletedAt(t *time.Time) *TestSessionAnswerCreate {
	if t != nil {
		tsac.SetDeletedAt(*t)
	}
	return tsac
}

// SetUserID sets the "user_id" field.
func (tsac *TestSessionAnswerCreate) SetUserID(u uuid.UUID) *TestSessionAnswerCreate {
	tsac.mutation.SetUserID(u)
	return tsac
}

// SetQuestionID sets the "question_id" field.
func (tsac *TestSessionAnswerCreate) SetQuestionID(u uuid.UUID) *TestSessionAnswerCreate {
	tsac.mutation.SetQuestionID(u)
	return tsac
}

// SetSelectedOptionID sets the "selected_option_id" field.
func (tsac *TestSessionAnswerCreate) SetSelectedOptionID(u uuid.UUID) *TestSessionAnswerCreate {
	tsac.mutation.SetSelectedOptionID(u)
	return tsac
}

// SetNillableSelectedOptionID sets the "selected_option_id" field if the given value is not nil.
func (tsac *TestSessionAnswerCreate) SetNillableSelectedOptionID(u *uuid.UUID) *TestSessionAnswerCreate {
	if u != nil {
		tsac.SetSelectedOptionID(*u)
	}
	return tsac
}

// SetSessionID sets the "session_id" field.
func (tsac *TestSessionAnswerCreate) SetSessionID(u uuid.UUID) *TestSessionAnswerCreate {
	tsac.mutation.SetSessionID(u)
	return tsac
}

// SetSelectedOptionText sets the "selected_option_text" field.
func (tsac *TestSessionAnswerCreate) SetSelectedOptionText(s string) *TestSessionAnswerCreate {
	tsac.mutation.SetSelectedOptionText(s)
	return tsac
}

// SetNillableSelectedOptionText sets the "selected_option_text" field if the given value is not nil.
func (tsac *TestSessionAnswerCreate) SetNillableSelectedOptionText(s *string) *TestSessionAnswerCreate {
	if s != nil {
		tsac.SetSelectedOptionText(*s)
	}
	return tsac
}

// SetID sets the "id" field.
func (tsac *TestSessionAnswerCreate) SetID(u uuid.UUID) *TestSessionAnswerCreate {
	tsac.mutation.SetID(u)
	return tsac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tsac *TestSessionAnswerCreate) SetNillableID(u *uuid.UUID) *TestSessionAnswerCreate {
	if u != nil {
		tsac.SetID(*u)
	}
	return tsac
}

// SetUser sets the "user" edge to the User entity.
func (tsac *TestSessionAnswerCreate) SetUser(u *User) *TestSessionAnswerCreate {
	return tsac.SetUserID(u.ID)
}

// SetQuestion sets the "question" edge to the Question entity.
func (tsac *TestSessionAnswerCreate) SetQuestion(q *Question) *TestSessionAnswerCreate {
	return tsac.SetQuestionID(q.ID)
}

// SetSelectedOption sets the "selected_option" edge to the QuestionOption entity.
func (tsac *TestSessionAnswerCreate) SetSelectedOption(q *QuestionOption) *TestSessionAnswerCreate {
	return tsac.SetSelectedOptionID(q.ID)
}

// SetTestSessionID sets the "test_session" edge to the TestSession entity by ID.
func (tsac *TestSessionAnswerCreate) SetTestSessionID(id uuid.UUID) *TestSessionAnswerCreate {
	tsac.mutation.SetTestSessionID(id)
	return tsac
}

// SetTestSession sets the "test_session" edge to the TestSession entity.
func (tsac *TestSessionAnswerCreate) SetTestSession(t *TestSession) *TestSessionAnswerCreate {
	return tsac.SetTestSessionID(t.ID)
}

// Mutation returns the TestSessionAnswerMutation object of the builder.
func (tsac *TestSessionAnswerCreate) Mutation() *TestSessionAnswerMutation {
	return tsac.mutation
}

// Save creates the TestSessionAnswer in the database.
func (tsac *TestSessionAnswerCreate) Save(ctx context.Context) (*TestSessionAnswer, error) {
	if err := tsac.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tsac.sqlSave, tsac.mutation, tsac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tsac *TestSessionAnswerCreate) SaveX(ctx context.Context) *TestSessionAnswer {
	v, err := tsac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tsac *TestSessionAnswerCreate) Exec(ctx context.Context) error {
	_, err := tsac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsac *TestSessionAnswerCreate) ExecX(ctx context.Context) {
	if err := tsac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tsac *TestSessionAnswerCreate) defaults() error {
	if _, ok := tsac.mutation.CreatedAt(); !ok {
		if testsessionanswer.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized testsessionanswer.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := testsessionanswer.DefaultCreatedAt()
		tsac.mutation.SetCreatedAt(v)
	}
	if _, ok := tsac.mutation.UpdatedAt(); !ok {
		if testsessionanswer.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized testsessionanswer.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := testsessionanswer.DefaultUpdatedAt()
		tsac.mutation.SetUpdatedAt(v)
	}
	if _, ok := tsac.mutation.ID(); !ok {
		if testsessionanswer.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized testsessionanswer.DefaultID (forgotten import ent/runtime?)")
		}
		v := testsessionanswer.DefaultID()
		tsac.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tsac *TestSessionAnswerCreate) check() error {
	if _, ok := tsac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TestSessionAnswer.created_at"`)}
	}
	if _, ok := tsac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TestSessionAnswer.updated_at"`)}
	}
	if _, ok := tsac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TestSessionAnswer.user_id"`)}
	}
	if _, ok := tsac.mutation.QuestionID(); !ok {
		return &ValidationError{Name: "question_id", err: errors.New(`ent: missing required field "TestSessionAnswer.question_id"`)}
	}
	if _, ok := tsac.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "TestSessionAnswer.session_id"`)}
	}
	if len(tsac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TestSessionAnswer.user"`)}
	}
	if len(tsac.mutation.QuestionIDs()) == 0 {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required edge "TestSessionAnswer.question"`)}
	}
	if len(tsac.mutation.TestSessionIDs()) == 0 {
		return &ValidationError{Name: "test_session", err: errors.New(`ent: missing required edge "TestSessionAnswer.test_session"`)}
	}
	return nil
}

func (tsac *TestSessionAnswerCreate) sqlSave(ctx context.Context) (*TestSessionAnswer, error) {
	if err := tsac.check(); err != nil {
		return nil, err
	}
	_node, _spec := tsac.createSpec()
	if err := sqlgraph.CreateNode(ctx, tsac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tsac.mutation.id = &_node.ID
	tsac.mutation.done = true
	return _node, nil
}

func (tsac *TestSessionAnswerCreate) createSpec() (*TestSessionAnswer, *sqlgraph.CreateSpec) {
	var (
		_node = &TestSessionAnswer{config: tsac.config}
		_spec = sqlgraph.NewCreateSpec(testsessionanswer.Table, sqlgraph.NewFieldSpec(testsessionanswer.FieldID, field.TypeUUID))
	)
	if id, ok := tsac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tsac.mutation.CreatedAt(); ok {
		_spec.SetField(testsessionanswer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tsac.mutation.UpdatedAt(); ok {
		_spec.SetField(testsessionanswer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tsac.mutation.DeletedAt(); ok {
		_spec.SetField(testsessionanswer.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := tsac.mutation.SelectedOptionText(); ok {
		_spec.SetField(testsessionanswer.FieldSelectedOptionText, field.TypeString, value)
		_node.SelectedOptionText = &value
	}
	if nodes := tsac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testsessionanswer.UserTable,
			Columns: []string{testsessionanswer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsac.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testsessionanswer.QuestionTable,
			Columns: []string{testsessionanswer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.QuestionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsac.mutation.SelectedOptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testsessionanswer.SelectedOptionTable,
			Columns: []string{testsessionanswer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questionoption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SelectedOptionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsac.mutation.TestSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testsessionanswer.TestSessionTable,
			Columns: []string{testsessionanswer.TestSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TestSessionAnswerCreateBulk is the builder for creating many TestSessionAnswer entities in bulk.
type TestSessionAnswerCreateBulk struct {
	config
	err      error
	builders []*TestSessionAnswerCreate
}

// Save creates the TestSessionAnswer entities in the database.
func (tsacb *TestSessionAnswerCreateBulk) Save(ctx context.Context) ([]*TestSessionAnswer, error) {
	if tsacb.err != nil {
		return nil, tsacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tsacb.builders))
	nodes := make([]*TestSessionAnswer, len(tsacb.builders))
	mutators := make([]Mutator, len(tsacb.builders))
	for i := range tsacb.builders {
		func(i int, root context.Context) {
			builder := tsacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TestSessionAnswerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tsacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tsacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tsacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tsacb *TestSessionAnswerCreateBulk) SaveX(ctx context.Context) []*TestSessionAnswer {
	v, err := tsacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tsacb *TestSessionAnswerCreateBulk) Exec(ctx context.Context) error {
	_, err := tsacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsacb *TestSessionAnswerCreateBulk) ExecX(ctx context.Context) {
	if err := tsacb.Exec(ctx); err != nil {
		panic(err)
	}
}
