// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"template/internal/ent/question"
	"template/internal/ent/test"
	"template/internal/ent/testignorequestion"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TestIgnoreQuestion is the model entity for the TestIgnoreQuestion schema.
type TestIgnoreQuestion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// TestID holds the value of the "test_id" field.
	TestID uuid.UUID `json:"test_id,omitempty"`
	// QuestionID holds the value of the "question_id" field.
	QuestionID uuid.UUID `json:"question_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TestIgnoreQuestionQuery when eager-loading is set.
	Edges        TestIgnoreQuestionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TestIgnoreQuestionEdges holds the relations/edges for other nodes in the graph.
type TestIgnoreQuestionEdges struct {
	// Test holds the value of the test edge.
	Test *Test `json:"test,omitempty"`
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TestOrErr returns the Test value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestIgnoreQuestionEdges) TestOrErr() (*Test, error) {
	if e.Test != nil {
		return e.Test, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: test.Label}
	}
	return nil, &NotLoadedError{edge: "test"}
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestIgnoreQuestionEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TestIgnoreQuestion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case testignorequestion.FieldReason:
			values[i] = new(sql.NullString)
		case testignorequestion.FieldCreatedAt, testignorequestion.FieldUpdatedAt, testignorequestion.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case testignorequestion.FieldID, testignorequestion.FieldTestID, testignorequestion.FieldQuestionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TestIgnoreQuestion fields.
func (tiq *TestIgnoreQuestion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case testignorequestion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tiq.ID = *value
			}
		case testignorequestion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tiq.CreatedAt = value.Time
			}
		case testignorequestion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tiq.UpdatedAt = value.Time
			}
		case testignorequestion.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				tiq.DeletedAt = new(time.Time)
				*tiq.DeletedAt = value.Time
			}
		case testignorequestion.FieldTestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field test_id", values[i])
			} else if value != nil {
				tiq.TestID = *value
			}
		case testignorequestion.FieldQuestionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field question_id", values[i])
			} else if value != nil {
				tiq.QuestionID = *value
			}
		case testignorequestion.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				tiq.Reason = new(string)
				*tiq.Reason = value.String
			}
		default:
			tiq.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TestIgnoreQuestion.
// This includes values selected through modifiers, order, etc.
func (tiq *TestIgnoreQuestion) Value(name string) (ent.Value, error) {
	return tiq.selectValues.Get(name)
}

// QueryTest queries the "test" edge of the TestIgnoreQuestion entity.
func (tiq *TestIgnoreQuestion) QueryTest() *TestQuery {
	return NewTestIgnoreQuestionClient(tiq.config).QueryTest(tiq)
}

// QueryQuestion queries the "question" edge of the TestIgnoreQuestion entity.
func (tiq *TestIgnoreQuestion) QueryQuestion() *QuestionQuery {
	return NewTestIgnoreQuestionClient(tiq.config).QueryQuestion(tiq)
}

// Update returns a builder for updating this TestIgnoreQuestion.
// Note that you need to call TestIgnoreQuestion.Unwrap() before calling this method if this TestIgnoreQuestion
// was returned from a transaction, and the transaction was committed or rolled back.
func (tiq *TestIgnoreQuestion) Update() *TestIgnoreQuestionUpdateOne {
	return NewTestIgnoreQuestionClient(tiq.config).UpdateOne(tiq)
}

// Unwrap unwraps the TestIgnoreQuestion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tiq *TestIgnoreQuestion) Unwrap() *TestIgnoreQuestion {
	_tx, ok := tiq.config.driver.(*txDriver)
	if !ok {
		panic("ent: TestIgnoreQuestion is not a transactional entity")
	}
	tiq.config.driver = _tx.drv
	return tiq
}

// String implements the fmt.Stringer.
func (tiq *TestIgnoreQuestion) String() string {
	var builder strings.Builder
	builder.WriteString("TestIgnoreQuestion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tiq.ID))
	builder.WriteString("created_at=")
	builder.WriteString(tiq.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tiq.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := tiq.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("test_id=")
	builder.WriteString(fmt.Sprintf("%v", tiq.TestID))
	builder.WriteString(", ")
	builder.WriteString("question_id=")
	builder.WriteString(fmt.Sprintf("%v", tiq.QuestionID))
	builder.WriteString(", ")
	if v := tiq.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// TestIgnoreQuestions is a parsable slice of TestIgnoreQuestion.
type TestIgnoreQuestions []*TestIgnoreQuestion
