package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"errors"
	"template/internal/features/auth"
	"template/internal/features/jwt"
	"template/internal/features/jwt_token"
	"template/internal/graph/model"

	"github.com/google/uuid"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (bool, error) {
	success, err := auth.Register(ctx, input)
	if err != nil {
		return false, err
	}
	return success, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.Auth, error) {
	user, err := auth.Login(ctx, input)
	if err != nil {
		return nil, err
	}

	// Generate token pair after successful authentication
	tokenPair, err := jwt.GenerateTokenPair(user.ID.String(), map[string]interface{}{
		"email":    user.Email,
		"username": user.Username,
	})
	if err != nil {
		return nil, err
	}

	// Save token pair to database
	_, err = jwt_token.SaveTokenPair(ctx, user.ID, tokenPair)
	if err != nil {
		return nil, err
	}

	return &model.Auth{
		AccessToken:  tokenPair.AccessToken,
		RefreshToken: tokenPair.RefreshToken,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// Extract the token from the request
	token, err := ExtractJwtTokenFromRequestContext(ctx)
	if err != nil {
		return false, err
	}

	// Revoke the token in the database
	err = jwt_token.RevokeToken(ctx, token)
	if err != nil {
		return false, err
	}

	return true, nil
}

// RenewToken is the resolver for the renewToken field.
func (r *mutationResolver) RenewToken(ctx context.Context, refreshToken string) (*model.Auth, error) {
	// Validate the refresh token
	tokenPair, err := jwt.RefreshTokenPair(refreshToken)
	if err != nil {
		return nil, errors.New("invalid refresh token")
	}

	// Get user ID from the refresh token to save new token
	claims, err := jwt.ValidateRefreshToken(refreshToken)
	if err != nil {
		return nil, errors.New("invalid refresh token")
	}

	// Parse user ID from claims
	userID, err := uuid.Parse(claims.UserID)
	if err != nil {
		return nil, errors.New("invalid user ID")
	}

	// Revoke the old refresh token
	err = jwt_token.RevokeTokenByRefreshToken(ctx, refreshToken)
	if err != nil {
		// Log the error but don't fail the operation if token doesn't exist
		// This could happen if token was already revoked
	}

	// Save new token pair to database
	_, err = jwt_token.SaveTokenPair(ctx, userID, tokenPair)
	if err != nil {
		return nil, err
	}

	return &model.Auth{
		AccessToken:  tokenPair.AccessToken,
		RefreshToken: tokenPair.RefreshToken,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	currentUser, err := GetUserFromRequestContext(ctx)
	if err != nil {
		return nil, err
	}

	return currentUser, nil
}

// IsAuthenticated is the resolver for the isAuthenticated field.
func (r *queryResolver) IsAuthenticated(ctx context.Context) (bool, error) {
	_, err := GetUserFromRequestContext(ctx)
	if err != nil {
		return false, nil
	}
	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
