query PaginateTests($paginationInput: PaginationInput) {
  paginatedTests(paginationInput: $paginationInput) {
    pagination {
      ...Pagination
    }
    items {
      ...TestFragment
    }
  }
} 