// Code generated by ent, DO NOT EDIT.

package question

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the question type in the database.
	Label = "question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCollectionID holds the string denoting the collection_id field in the database.
	FieldCollectionID = "collection_id"
	// FieldQuestionText holds the string denoting the question_text field in the database.
	FieldQuestionText = "question_text"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// EdgeCollection holds the string denoting the collection edge name in mutations.
	EdgeCollection = "collection"
	// EdgeQuestionOptions holds the string denoting the question_options edge name in mutations.
	EdgeQuestionOptions = "question_options"
	// EdgeVideoQuestionTimestampsQuestion holds the string denoting the video_question_timestamps_question edge name in mutations.
	EdgeVideoQuestionTimestampsQuestion = "video_question_timestamps_question"
	// EdgeUserQuestionAnswers holds the string denoting the user_question_answers edge name in mutations.
	EdgeUserQuestionAnswers = "user_question_answers"
	// EdgeTestIgnoreQuestions holds the string denoting the test_ignore_questions edge name in mutations.
	EdgeTestIgnoreQuestions = "test_ignore_questions"
	// Table holds the table name of the question in the database.
	Table = "questions"
	// CollectionTable is the table that holds the collection relation/edge.
	CollectionTable = "questions"
	// CollectionInverseTable is the table name for the QuestionCollection entity.
	// It exists in this package in order to avoid circular dependency with the "questioncollection" package.
	CollectionInverseTable = "question_collections"
	// CollectionColumn is the table column denoting the collection relation/edge.
	CollectionColumn = "collection_id"
	// QuestionOptionsTable is the table that holds the question_options relation/edge.
	QuestionOptionsTable = "question_options"
	// QuestionOptionsInverseTable is the table name for the QuestionOption entity.
	// It exists in this package in order to avoid circular dependency with the "questionoption" package.
	QuestionOptionsInverseTable = "question_options"
	// QuestionOptionsColumn is the table column denoting the question_options relation/edge.
	QuestionOptionsColumn = "question_id"
	// VideoQuestionTimestampsQuestionTable is the table that holds the video_question_timestamps_question relation/edge.
	VideoQuestionTimestampsQuestionTable = "video_question_timestamps"
	// VideoQuestionTimestampsQuestionInverseTable is the table name for the VideoQuestionTimestamp entity.
	// It exists in this package in order to avoid circular dependency with the "videoquestiontimestamp" package.
	VideoQuestionTimestampsQuestionInverseTable = "video_question_timestamps"
	// VideoQuestionTimestampsQuestionColumn is the table column denoting the video_question_timestamps_question relation/edge.
	VideoQuestionTimestampsQuestionColumn = "question_id"
	// UserQuestionAnswersTable is the table that holds the user_question_answers relation/edge.
	UserQuestionAnswersTable = "test_session_answers"
	// UserQuestionAnswersInverseTable is the table name for the TestSessionAnswer entity.
	// It exists in this package in order to avoid circular dependency with the "testsessionanswer" package.
	UserQuestionAnswersInverseTable = "test_session_answers"
	// UserQuestionAnswersColumn is the table column denoting the user_question_answers relation/edge.
	UserQuestionAnswersColumn = "question_id"
	// TestIgnoreQuestionsTable is the table that holds the test_ignore_questions relation/edge.
	TestIgnoreQuestionsTable = "test_ignore_questions"
	// TestIgnoreQuestionsInverseTable is the table name for the TestIgnoreQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "testignorequestion" package.
	TestIgnoreQuestionsInverseTable = "test_ignore_questions"
	// TestIgnoreQuestionsColumn is the table column denoting the test_ignore_questions relation/edge.
	TestIgnoreQuestionsColumn = "question_id"
)

// Columns holds all SQL columns for question fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCollectionID,
	FieldQuestionText,
	FieldPoints,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "template/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// QuestionTextValidator is a validator for the "question_text" field. It is called by the builders before save.
	QuestionTextValidator func(string) error
	// DefaultPoints holds the default value on creation for the "points" field.
	DefaultPoints int
	// PointsValidator is a validator for the "points" field. It is called by the builders before save.
	PointsValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Question queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCollectionID orders the results by the collection_id field.
func ByCollectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionID, opts...).ToFunc()
}

// ByQuestionText orders the results by the question_text field.
func ByQuestionText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionText, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByCollectionField orders the results by collection field.
func ByCollectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCollectionStep(), sql.OrderByField(field, opts...))
	}
}

// ByQuestionOptionsCount orders the results by question_options count.
func ByQuestionOptionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuestionOptionsStep(), opts...)
	}
}

// ByQuestionOptions orders the results by question_options terms.
func ByQuestionOptions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionOptionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVideoQuestionTimestampsQuestionCount orders the results by video_question_timestamps_question count.
func ByVideoQuestionTimestampsQuestionCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVideoQuestionTimestampsQuestionStep(), opts...)
	}
}

// ByVideoQuestionTimestampsQuestion orders the results by video_question_timestamps_question terms.
func ByVideoQuestionTimestampsQuestion(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVideoQuestionTimestampsQuestionStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserQuestionAnswersCount orders the results by user_question_answers count.
func ByUserQuestionAnswersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserQuestionAnswersStep(), opts...)
	}
}

// ByUserQuestionAnswers orders the results by user_question_answers terms.
func ByUserQuestionAnswers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserQuestionAnswersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTestIgnoreQuestionsCount orders the results by test_ignore_questions count.
func ByTestIgnoreQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestIgnoreQuestionsStep(), opts...)
	}
}

// ByTestIgnoreQuestions orders the results by test_ignore_questions terms.
func ByTestIgnoreQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestIgnoreQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCollectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CollectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CollectionTable, CollectionColumn),
	)
}
func newQuestionOptionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionOptionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuestionOptionsTable, QuestionOptionsColumn),
	)
}
func newVideoQuestionTimestampsQuestionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VideoQuestionTimestampsQuestionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VideoQuestionTimestampsQuestionTable, VideoQuestionTimestampsQuestionColumn),
	)
}
func newUserQuestionAnswersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserQuestionAnswersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserQuestionAnswersTable, UserQuestionAnswersColumn),
	)
}
func newTestIgnoreQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestIgnoreQuestionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TestIgnoreQuestionsTable, TestIgnoreQuestionsColumn),
	)
}
