mutation CreateQuestion($input: CreateQuestionInput!) {
  createQuestion(input: $input) {
    ...QuestionItem
    options {
      ...QuestionOptionItem
    }
    collection {
      ...QuestionCollectionItem
    }
  }
} 