query GetQuestionsByCollectionId($collectionId: ID!) {
  questionCollection(id: $collectionId) {
    ...QuestionCollectionItem
    questions {
      ...QuestionItem
      options {
        ...QuestionOptionItem
      }
    }
  }
} 