extend type Mutation {
  login(input: LoginInput!): Auth!
  register(input: RegisterInput!): Auth!
  renewToken(refreshToken: String!): Auth!
}


type Auth {
  accessToken: String!
  refreshToken: String!
}


input LoginInput {
  email: String!
  password: String!
}

input RegisterInput {
  email: String!
  password: String!
}



