extend type Mutation {
  createCourseSession(input: CreateCourseSessionInput!): CourseSession!
  updateCourseSession(id: ID!, input: UpdateCourseSessionInput!): CourseSession!
  removeCourseSession(id: ID!): Boolean!
}

extend type Query {
  courseSession(id: ID!): CourseSession!
  paginatedCourseSessions(input: PaginationInput): PaginatedCourseSession!
}

type CourseSession {
  id: ID!
  courseId: ID!
  totalScore: Int!
}

input CreateCourseSessionInput {
  courseId: ID!
}

input UpdateCourseSessionInput {
  totalScore: Int
}

type PaginatedCourseSession {
  pagination: Pagination!
  items: [CourseSession!]!
}
