extend type Mutation {
  createCourseSection(input: CreateCourseSectionInput!): CourseSection!
  updateCourseSection(id: ID!, input: UpdateCourseSectionInput!): CourseSection!
  removeCourseSection(id: ID!): Boolean!
}

extend type Query {
  courseSection(id: ID!): CourseSection!
  paginatedCourseSections(input: PaginationInput): PaginatedCourseSection!
}


type CourseSection {
  id: ID!
  title: String!
  description: String!
}

input CreateCourseSectionInput {
  title: String!
  description: String!
}

input UpdateCourseSectionInput {
  title: String
  description: String
}

type PaginatedCourseSection {
  pagination: Pagination!
  items: [CourseSection!]!
}
