extend type Mutation {
  createCourseSection(input: CreateCourseSectionInput!): CourseSection!
  updateCourseSection(id: ID!, input: UpdateCourseSectionInput!): CourseSection!
  removeCourseSection(id: ID!): Boolean!
}

extend type Query {
  courseSection(id: ID!): CourseSection!
  courseSectionsByCourseId(courseId: ID!): [CourseSection!]!
}


type CourseSection {
  id: ID!
  title: String!
  description: String!
  courseId: ID!
}

input CreateCourseSectionInput {
  title: String!
  description: String!
  courseId: ID!
}

input UpdateCourseSectionInput {
  title: String
  description: String
}

