extend type Mutation {
  createQuestionOption(input: CreateQuestionOptionInput!): QuestionOption!
  updateQuestionOption(id: ID!, input: UpdateQuestionOptionInput!): QuestionOption!
  deleteQuestionOption(id: ID!): Boolean!
}

extend type Query {
  questionOption(id: ID!): QuestionOption!
}

type QuestionOption {
  id: ID!
  question: Question!
  optionText: String!
  isCorrect: Boolean!
}

type PaginatedQuestionOption {
  pagination: Pagination!
  items: [QuestionOption!]!
}

input CreateQuestionOptionInput {
  questionId: ID!
  optionText: String!
  isCorrect: Boolean!
}

input UpdateQuestionOptionInput {
  optionText: String
  isCorrect: Boolean
} 