extend type Mutation {
  createTestSession(input: CreateTestSessionInput!): TestSession!
  deleteTestSession(id: ID!): Boolean!
  completeTestSession(id: ID!): TestSession!
}

extend type Query {
  testSession(id: ID!): TestSession!
}

type TestSession {
  id: ID!
  user: User!
  test: Test!
  completedAt: DateTime
  maxPoints: Int!
  pointsEarned: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type PaginatedTestSession {
  pagination: Pagination!
  items: [TestSession!]!
}

input CreateTestSessionInput {
  testId: ID!
  courseSectionId: ID
}

input UpdateTestSessionInput {
  completedAt: DateTime
  totalScore: Int
} 