extend type Query {
  paginatedUsers(paginationInput: PaginationInput): PaginatedUser!
}

type User {
  id: ID!
  email: String!
  username: String!
  firstName: String
  lastName: String
  isActive: Boolean!
  roles: [Role!]!
  permissions: [Permission!]!
}

type Role {
  id: ID!
  name: String!
}

type PaginatedUser {
  pagination: Pagination!
  items: [User!]!
}
