// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"template/internal/ent/question"
	"template/internal/ent/testsession"
	"template/internal/ent/testsessionanswer"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TestSessionAnswer is the model entity for the TestSessionAnswer schema.
type TestSessionAnswer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// QuestionID holds the value of the "question_id" field.
	QuestionID uuid.UUID `json:"question_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// Points holds the value of the "points" field.
	Points *int `json:"points,omitempty"`
	// Order holds the value of the "order" field.
	Order int `json:"order,omitempty"`
	// IsCorrect holds the value of the "is_correct" field.
	IsCorrect *bool `json:"is_correct,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TestSessionAnswerQuery when eager-loading is set.
	Edges        TestSessionAnswerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TestSessionAnswerEdges holds the relations/edges for other nodes in the graph.
type TestSessionAnswerEdges struct {
	// Question holds the value of the question edge.
	Question *Question `json:"question,omitempty"`
	// TestSession holds the value of the test_session edge.
	TestSession *TestSession `json:"test_session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestSessionAnswerEdges) QuestionOrErr() (*Question, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: question.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// TestSessionOrErr returns the TestSession value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TestSessionAnswerEdges) TestSessionOrErr() (*TestSession, error) {
	if e.TestSession != nil {
		return e.TestSession, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: testsession.Label}
	}
	return nil, &NotLoadedError{edge: "test_session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TestSessionAnswer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case testsessionanswer.FieldIsCorrect:
			values[i] = new(sql.NullBool)
		case testsessionanswer.FieldPoints, testsessionanswer.FieldOrder:
			values[i] = new(sql.NullInt64)
		case testsessionanswer.FieldCreatedAt, testsessionanswer.FieldUpdatedAt, testsessionanswer.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case testsessionanswer.FieldID, testsessionanswer.FieldQuestionID, testsessionanswer.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TestSessionAnswer fields.
func (tsa *TestSessionAnswer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case testsessionanswer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tsa.ID = *value
			}
		case testsessionanswer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tsa.CreatedAt = value.Time
			}
		case testsessionanswer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tsa.UpdatedAt = value.Time
			}
		case testsessionanswer.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				tsa.DeletedAt = new(time.Time)
				*tsa.DeletedAt = value.Time
			}
		case testsessionanswer.FieldQuestionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field question_id", values[i])
			} else if value != nil {
				tsa.QuestionID = *value
			}
		case testsessionanswer.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				tsa.SessionID = *value
			}
		case testsessionanswer.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				tsa.Points = new(int)
				*tsa.Points = int(value.Int64)
			}
		case testsessionanswer.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				tsa.Order = int(value.Int64)
			}
		case testsessionanswer.FieldIsCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_correct", values[i])
			} else if value.Valid {
				tsa.IsCorrect = new(bool)
				*tsa.IsCorrect = value.Bool
			}
		default:
			tsa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TestSessionAnswer.
// This includes values selected through modifiers, order, etc.
func (tsa *TestSessionAnswer) Value(name string) (ent.Value, error) {
	return tsa.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the TestSessionAnswer entity.
func (tsa *TestSessionAnswer) QueryQuestion() *QuestionQuery {
	return NewTestSessionAnswerClient(tsa.config).QueryQuestion(tsa)
}

// QueryTestSession queries the "test_session" edge of the TestSessionAnswer entity.
func (tsa *TestSessionAnswer) QueryTestSession() *TestSessionQuery {
	return NewTestSessionAnswerClient(tsa.config).QueryTestSession(tsa)
}

// Update returns a builder for updating this TestSessionAnswer.
// Note that you need to call TestSessionAnswer.Unwrap() before calling this method if this TestSessionAnswer
// was returned from a transaction, and the transaction was committed or rolled back.
func (tsa *TestSessionAnswer) Update() *TestSessionAnswerUpdateOne {
	return NewTestSessionAnswerClient(tsa.config).UpdateOne(tsa)
}

// Unwrap unwraps the TestSessionAnswer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tsa *TestSessionAnswer) Unwrap() *TestSessionAnswer {
	_tx, ok := tsa.config.driver.(*txDriver)
	if !ok {
		panic("ent: TestSessionAnswer is not a transactional entity")
	}
	tsa.config.driver = _tx.drv
	return tsa
}

// String implements the fmt.Stringer.
func (tsa *TestSessionAnswer) String() string {
	var builder strings.Builder
	builder.WriteString("TestSessionAnswer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tsa.ID))
	builder.WriteString("created_at=")
	builder.WriteString(tsa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tsa.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := tsa.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("question_id=")
	builder.WriteString(fmt.Sprintf("%v", tsa.QuestionID))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", tsa.SessionID))
	builder.WriteString(", ")
	if v := tsa.Points; v != nil {
		builder.WriteString("points=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("order=")
	builder.WriteString(fmt.Sprintf("%v", tsa.Order))
	builder.WriteString(", ")
	if v := tsa.IsCorrect; v != nil {
		builder.WriteString("is_correct=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TestSessionAnswers is a parsable slice of TestSessionAnswer.
type TestSessionAnswers []*TestSessionAnswer
