// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type AddMultiCollectionToTestInput struct {
	TestID        uuid.UUID   `json:"testId"`
	CollectionIds []uuid.UUID `json:"collectionIds"`
}

type Auth struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type BatchIgnoreQuestionsInput struct {
	TestID             uuid.UUID             `json:"testId"`
	QuestionIgnoreData []*QuestionIgnoreData `json:"questionIgnoreData"`
}

type CourseSectionFilterInput struct {
	OnlyRoot *bool `json:"onlyRoot,omitempty"`
}

type CreateCourseInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type CreateCourseSectionInput struct {
	Title       string     `json:"title"`
	Description string     `json:"description"`
	CourseID    uuid.UUID  `json:"courseId"`
	SectionID   *uuid.UUID `json:"sectionId,omitempty"`
}

type CreateQuestionCollectionInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type CreateQuestionInput struct {
	QuestionText         string                 `json:"questionText"`
	QuestionCollectionID uuid.UUID              `json:"questionCollectionId"`
	Options              []*QuestionOptionInput `json:"options"`
}

type CreateQuestionOptionInput struct {
	QuestionID uuid.UUID `json:"questionId"`
	OptionText string    `json:"optionText"`
	IsCorrect  bool      `json:"isCorrect"`
}

type CreateTestInput struct {
	Name            string      `json:"name"`
	CourseSectionID *uuid.UUID  `json:"courseSectionId,omitempty"`
	CourseID        *uuid.UUID  `json:"courseId,omitempty"`
	QuestionIds     []uuid.UUID `json:"questionIds"`
}

type CreateTestSessionInput struct {
	TestID          uuid.UUID  `json:"testId"`
	CourseSectionID *uuid.UUID `json:"courseSectionId,omitempty"`
}

type CreateUserQuestionAnswerInput struct {
	UserID           uuid.UUID `json:"userId"`
	QuestionID       uuid.UUID `json:"questionId"`
	SelectedOptionID uuid.UUID `json:"selectedOptionId"`
	TestSessionID    uuid.UUID `json:"testSessionId"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewTodo struct {
	Text string `json:"text"`
}

type PaginatedCourse struct {
	Pagination *Pagination `json:"pagination"`
	Items      []*Course   `json:"items"`
}

type PaginatedQuestion struct {
	Pagination *Pagination `json:"pagination"`
	Items      []*Question `json:"items"`
}

type PaginatedQuestionCollection struct {
	Pagination *Pagination           `json:"pagination"`
	Items      []*QuestionCollection `json:"items"`
}

type PaginatedQuestionOption struct {
	Pagination *Pagination       `json:"pagination"`
	Items      []*QuestionOption `json:"items"`
}

type PaginatedTest struct {
	Pagination *Pagination `json:"pagination"`
	Items      []*Test     `json:"items"`
}

type PaginatedTestSession struct {
	Pagination *Pagination    `json:"pagination"`
	Items      []*TestSession `json:"items"`
}

type PaginatedUserQuestionAnswer struct {
	Pagination *Pagination           `json:"pagination"`
	Items      []*UserQuestionAnswer `json:"items"`
}

type Pagination struct {
	CurrentPage     int  `json:"currentPage"`
	TotalPages      int  `json:"totalPages"`
	TotalItems      int  `json:"totalItems"`
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type PaginationInput struct {
	Page   *int    `json:"page,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Search *string `json:"search,omitempty"`
}

type Query struct {
}

type QuestionIgnoreData struct {
	QuestionID uuid.UUID `json:"questionId"`
	Reason     *string   `json:"reason,omitempty"`
}

type QuestionOptionInput struct {
	OptionText string `json:"optionText"`
	IsCorrect  bool   `json:"isCorrect"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type TestIgnoreQuestion struct {
	ID         uuid.UUID `json:"id"`
	TestID     uuid.UUID `json:"testId"`
	QuestionID uuid.UUID `json:"questionId"`
	Reason     *string   `json:"reason,omitempty"`
	Question   *Question `json:"question,omitempty"`
}

type TestQuestionCount struct {
	ID                uuid.UUID `json:"id"`
	TestID            uuid.UUID `json:"testId"`
	NumberOfQuestions int       `json:"numberOfQuestions"`
	Points            int       `json:"points"`
}

type TestQuestionPoint struct {
	ID         uuid.UUID `json:"id"`
	TestID     uuid.UUID `json:"testId"`
	QuestionID uuid.UUID `json:"questionId"`
	Points     int       `json:"points"`
	Question   *Question `json:"question,omitempty"`
}

type Todo struct {
	ID   uuid.UUID `json:"id"`
	Text string    `json:"text"`
}

type UpdateBatchQuestionsByCollectionInput struct {
	CollectionID uuid.UUID             `json:"collectionId"`
	Questions    []*UpdateQuestionData `json:"questions"`
}

type UpdateCourseInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateCourseSectionInput struct {
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	SectionID   *uuid.UUID `json:"sectionId,omitempty"`
}

type UpdateQuestionCollectionInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateQuestionData struct {
	ID           *uuid.UUID                   `json:"id,omitempty"`
	QuestionText *string                      `json:"questionText,omitempty"`
	Options      []*UpdateQuestionOptionInput `json:"options"`
}

type UpdateQuestionInput struct {
	QuestionText         *string                `json:"questionText,omitempty"`
	QuestionCollectionID *uuid.UUID             `json:"questionCollectionId,omitempty"`
	Options              []*QuestionOptionInput `json:"options,omitempty"`
}

type UpdateQuestionOptionInput struct {
	OptionText *string `json:"optionText,omitempty"`
	IsCorrect  *bool   `json:"isCorrect,omitempty"`
}

type UpdateQuestionPointsByCollectionInput struct {
	TestID       uuid.UUID `json:"testId"`
	CollectionID uuid.UUID `json:"collectionId"`
	Points       int       `json:"points"`
}

type UpdateQuestionPointsInput struct {
	TestID     uuid.UUID `json:"testId"`
	QuestionID uuid.UUID `json:"questionId"`
	Points     int       `json:"points"`
}

type UpdateTestInput struct {
	Name            *string     `json:"name,omitempty"`
	CourseSectionID *uuid.UUID  `json:"courseSectionId,omitempty"`
	CourseID        *uuid.UUID  `json:"courseId,omitempty"`
	QuestionIds     []uuid.UUID `json:"questionIds"`
}

type UpdateTestQuestionRequirementInput struct {
	TestID            uuid.UUID `json:"testId"`
	NumberOfQuestions int       `json:"numberOfQuestions"`
	PointsPerQuestion int       `json:"pointsPerQuestion"`
}

type UpdateTestSessionInput struct {
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	TotalScore  *int       `json:"totalScore,omitempty"`
}

type UpdateUserQuestionAnswerInput struct {
	SelectedOptionID *uuid.UUID `json:"selectedOptionId,omitempty"`
}

type User struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

type UserQuestionAnswer struct {
	ID             uuid.UUID       `json:"id"`
	User           *User           `json:"user"`
	Question       *Question       `json:"question"`
	SelectedOption *QuestionOption `json:"selectedOption"`
	TestSession    *TestSession    `json:"testSession"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}
