// Code generated by ent, DO NOT EDIT.

package test

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the test type in the database.
	Label = "test"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCourseSectionID holds the string denoting the course_section_id field in the database.
	FieldCourseSectionID = "course_section_id"
	// FieldCourseID holds the string denoting the course_id field in the database.
	FieldCourseID = "course_id"
	// FieldTotalPoints holds the string denoting the total_points field in the database.
	FieldTotalPoints = "total_points"
	// EdgeCourseSection holds the string denoting the course_section edge name in mutations.
	EdgeCourseSection = "course_section"
	// EdgeCourse holds the string denoting the course edge name in mutations.
	EdgeCourse = "course"
	// EdgeTestSessions holds the string denoting the test_sessions edge name in mutations.
	EdgeTestSessions = "test_sessions"
	// EdgeQuestions holds the string denoting the questions edge name in mutations.
	EdgeQuestions = "questions"
	// EdgeQuestionCollections holds the string denoting the question_collections edge name in mutations.
	EdgeQuestionCollections = "question_collections"
	// EdgeTestQuestionCounts holds the string denoting the test_question_counts edge name in mutations.
	EdgeTestQuestionCounts = "test_question_counts"
	// EdgeTestIgnoreQuestions holds the string denoting the test_ignore_questions edge name in mutations.
	EdgeTestIgnoreQuestions = "test_ignore_questions"
	// EdgeTestQuestionPoints holds the string denoting the test_question_points edge name in mutations.
	EdgeTestQuestionPoints = "test_question_points"
	// Table holds the table name of the test in the database.
	Table = "tests"
	// CourseSectionTable is the table that holds the course_section relation/edge.
	CourseSectionTable = "tests"
	// CourseSectionInverseTable is the table name for the CourseSection entity.
	// It exists in this package in order to avoid circular dependency with the "coursesection" package.
	CourseSectionInverseTable = "course_sections"
	// CourseSectionColumn is the table column denoting the course_section relation/edge.
	CourseSectionColumn = "course_section_id"
	// CourseTable is the table that holds the course relation/edge.
	CourseTable = "tests"
	// CourseInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CourseInverseTable = "courses"
	// CourseColumn is the table column denoting the course relation/edge.
	CourseColumn = "course_id"
	// TestSessionsTable is the table that holds the test_sessions relation/edge.
	TestSessionsTable = "test_sessions"
	// TestSessionsInverseTable is the table name for the TestSession entity.
	// It exists in this package in order to avoid circular dependency with the "testsession" package.
	TestSessionsInverseTable = "test_sessions"
	// TestSessionsColumn is the table column denoting the test_sessions relation/edge.
	TestSessionsColumn = "test_id"
	// QuestionsTable is the table that holds the questions relation/edge. The primary key declared below.
	QuestionsTable = "test_questions"
	// QuestionsInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	QuestionsInverseTable = "questions"
	// QuestionCollectionsTable is the table that holds the question_collections relation/edge. The primary key declared below.
	QuestionCollectionsTable = "test_question_collections"
	// QuestionCollectionsInverseTable is the table name for the QuestionCollection entity.
	// It exists in this package in order to avoid circular dependency with the "questioncollection" package.
	QuestionCollectionsInverseTable = "question_collections"
	// TestQuestionCountsTable is the table that holds the test_question_counts relation/edge.
	TestQuestionCountsTable = "test_question_counts"
	// TestQuestionCountsInverseTable is the table name for the TestQuestionCount entity.
	// It exists in this package in order to avoid circular dependency with the "testquestioncount" package.
	TestQuestionCountsInverseTable = "test_question_counts"
	// TestQuestionCountsColumn is the table column denoting the test_question_counts relation/edge.
	TestQuestionCountsColumn = "test_id"
	// TestIgnoreQuestionsTable is the table that holds the test_ignore_questions relation/edge.
	TestIgnoreQuestionsTable = "test_ignore_questions"
	// TestIgnoreQuestionsInverseTable is the table name for the TestIgnoreQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "testignorequestion" package.
	TestIgnoreQuestionsInverseTable = "test_ignore_questions"
	// TestIgnoreQuestionsColumn is the table column denoting the test_ignore_questions relation/edge.
	TestIgnoreQuestionsColumn = "test_id"
	// TestQuestionPointsTable is the table that holds the test_question_points relation/edge.
	TestQuestionPointsTable = "test_question_points"
	// TestQuestionPointsInverseTable is the table name for the TestQuestionPoint entity.
	// It exists in this package in order to avoid circular dependency with the "testquestionpoint" package.
	TestQuestionPointsInverseTable = "test_question_points"
	// TestQuestionPointsColumn is the table column denoting the test_question_points relation/edge.
	TestQuestionPointsColumn = "test_id"
)

// Columns holds all SQL columns for test fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldCourseSectionID,
	FieldCourseID,
	FieldTotalPoints,
}

var (
	// QuestionsPrimaryKey and QuestionsColumn2 are the table columns denoting the
	// primary key for the questions relation (M2M).
	QuestionsPrimaryKey = []string{"test_id", "question_id"}
	// QuestionCollectionsPrimaryKey and QuestionCollectionsColumn2 are the table columns denoting the
	// primary key for the question_collections relation (M2M).
	QuestionCollectionsPrimaryKey = []string{"test_id", "question_collection_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "template/internal/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultTotalPoints holds the default value on creation for the "total_points" field.
	DefaultTotalPoints int
	// TotalPointsValidator is a validator for the "total_points" field. It is called by the builders before save.
	TotalPointsValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Test queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCourseSectionID orders the results by the course_section_id field.
func ByCourseSectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourseSectionID, opts...).ToFunc()
}

// ByCourseID orders the results by the course_id field.
func ByCourseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourseID, opts...).ToFunc()
}

// ByTotalPoints orders the results by the total_points field.
func ByTotalPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPoints, opts...).ToFunc()
}

// ByCourseSectionField orders the results by course_section field.
func ByCourseSectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCourseSectionStep(), sql.OrderByField(field, opts...))
	}
}

// ByCourseField orders the results by course field.
func ByCourseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCourseStep(), sql.OrderByField(field, opts...))
	}
}

// ByTestSessionsCount orders the results by test_sessions count.
func ByTestSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestSessionsStep(), opts...)
	}
}

// ByTestSessions orders the results by test_sessions terms.
func ByTestSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuestionsCount orders the results by questions count.
func ByQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuestionsStep(), opts...)
	}
}

// ByQuestions orders the results by questions terms.
func ByQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuestionCollectionsCount orders the results by question_collections count.
func ByQuestionCollectionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuestionCollectionsStep(), opts...)
	}
}

// ByQuestionCollections orders the results by question_collections terms.
func ByQuestionCollections(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionCollectionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTestQuestionCountsCount orders the results by test_question_counts count.
func ByTestQuestionCountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestQuestionCountsStep(), opts...)
	}
}

// ByTestQuestionCounts orders the results by test_question_counts terms.
func ByTestQuestionCounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestQuestionCountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTestIgnoreQuestionsCount orders the results by test_ignore_questions count.
func ByTestIgnoreQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestIgnoreQuestionsStep(), opts...)
	}
}

// ByTestIgnoreQuestions orders the results by test_ignore_questions terms.
func ByTestIgnoreQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestIgnoreQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTestQuestionPointsCount orders the results by test_question_points count.
func ByTestQuestionPointsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestQuestionPointsStep(), opts...)
	}
}

// ByTestQuestionPoints orders the results by test_question_points terms.
func ByTestQuestionPoints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestQuestionPointsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCourseSectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CourseSectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CourseSectionTable, CourseSectionColumn),
	)
}
func newCourseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CourseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
	)
}
func newTestSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TestSessionsTable, TestSessionsColumn),
	)
}
func newQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, QuestionsTable, QuestionsPrimaryKey...),
	)
}
func newQuestionCollectionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionCollectionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, QuestionCollectionsTable, QuestionCollectionsPrimaryKey...),
	)
}
func newTestQuestionCountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestQuestionCountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TestQuestionCountsTable, TestQuestionCountsColumn),
	)
}
func newTestIgnoreQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestIgnoreQuestionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TestIgnoreQuestionsTable, TestIgnoreQuestionsColumn),
	)
}
func newTestQuestionPointsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestQuestionPointsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TestQuestionPointsTable, TestQuestionPointsColumn),
	)
}
