package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"template/internal/graph/model"
)

// CreateCourseSection is the resolver for the createCourseSection field.
func (r *mutationResolver) CreateCourseSection(ctx context.Context, input model.CreateCourseSectionInput) (*model.CourseSection, error) {
	panic(fmt.Errorf("not implemented: CreateCourseSection - createCourseSection"))
}

// UpdateCourseSection is the resolver for the updateCourseSection field.
func (r *mutationResolver) UpdateCourseSection(ctx context.Context, id string, input model.UpdateCourseSectionInput) (*model.CourseSection, error) {
	panic(fmt.Errorf("not implemented: UpdateCourseSection - updateCourseSection"))
}

// RemoveCourseSection is the resolver for the removeCourseSection field.
func (r *mutationResolver) RemoveCourseSection(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveCourseSection - removeCourseSection"))
}

// CourseSection is the resolver for the courseSection field.
func (r *queryResolver) CourseSection(ctx context.Context, id string) (*model.CourseSection, error) {
	panic(fmt.Errorf("not implemented: CourseSection - courseSection"))
}

// PaginatedCourseSections is the resolver for the paginatedCourseSections field.
func (r *queryResolver) PaginatedCourseSections(ctx context.Context, input *model.PaginationInput) (*model.PaginatedCourseSection, error) {
	panic(fmt.Errorf("not implemented: PaginatedCourseSections - paginatedCourseSections"))
}
