package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"template/internal/features/course_section"
	"template/internal/graph/model"

	"github.com/google/uuid"
)

// CreateCourseSection is the resolver for the createCourseSection field.
func (r *mutationResolver) CreateCourseSection(ctx context.Context, input model.CreateCourseSectionInput) (*model.CourseSection, error) {
	userId, err := GetUserIdFromRequestContext(ctx)
	if err != nil {
		return nil, err
	}

	cid, err := uuid.Parse(input.CourseID)
	if err != nil {
		return nil, err
	}
	cs, err := course_section.CreateCourseSection(ctx, userId, cid, input)
	if err != nil {
		return nil, err
	}
	return model.ConvertCourseSectionToModel(cs), nil
}

// UpdateCourseSection is the resolver for the updateCourseSection field.
func (r *mutationResolver) UpdateCourseSection(ctx context.Context, id string, input model.UpdateCourseSectionInput) (*model.CourseSection, error) {
	userId, err := GetUserIdFromRequestContext(ctx)
	if err != nil {
		return nil, err
	}
	sectionUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	courseSection, err := course_section.UpdateCourseSection(ctx, userId, sectionUUID, input)
	if err != nil {
		return nil, err
	}
	return model.ConvertCourseSectionToModel(courseSection), nil
}

// RemoveCourseSection is the resolver for the removeCourseSection field.
func (r *mutationResolver) RemoveCourseSection(ctx context.Context, id string) (bool, error) {
	userId, err := GetUserIdFromRequestContext(ctx)
	if err != nil {
		return false, err
	}
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}
	return course_section.RemoveCourseSection(ctx, userId, uid)
}

// CourseSection is the resolver for the courseSection field.
func (r *queryResolver) CourseSection(ctx context.Context, id string) (*model.CourseSection, error) {
	userId, err := GetUserIdFromRequestContext(ctx)
	if err != nil {
		return nil, err
	}
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	cs, err := course_section.GetCourseSectionByID(ctx, userId, uid)
	if err != nil {
		return nil, err
	}
	return model.ConvertCourseSectionToModel(cs), nil
}
