package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"template/internal/graph/model"

	"github.com/google/uuid"
)

// CreateTest is the resolver for the createTest field.
func (r *mutationResolver) CreateTest(ctx context.Context, input model.CreateTestInput) (*model.Test, error) {
	panic(fmt.Errorf("not implemented: CreateTest - createTest"))
}

// UpdateTest is the resolver for the updateTest field.
func (r *mutationResolver) UpdateTest(ctx context.Context, id uuid.UUID, input model.UpdateTestInput) (*model.Test, error) {
	panic(fmt.Errorf("not implemented: UpdateTest - updateTest"))
}

// DeleteTest is the resolver for the deleteTest field.
func (r *mutationResolver) DeleteTest(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTest - deleteTest"))
}

// Test is the resolver for the test field.
func (r *queryResolver) Test(ctx context.Context, id uuid.UUID) (*model.Test, error) {
	panic(fmt.Errorf("not implemented: Test - test"))
}

// PaginatedTests is the resolver for the paginatedTests field.
func (r *queryResolver) PaginatedTests(ctx context.Context, paginationInput *model.PaginationInput) (*model.PaginatedTest, error) {
	panic(fmt.Errorf("not implemented: PaginatedTests - paginatedTests"))
}
