query PaginateCourses($paginationInput: PaginationInput) {
  paginatedCourses(paginationInput: $paginationInput) {
    pagination {
      ...Pagination
    }
    items {
      ...CourseItem
    }
  }
}