export const APP_ROUTES = {
  dashboard: '/dashboard',
  courses: '/courses',
  profile: '/profile',
  login: '/login',
  adminCourses: '/admin/courses',
  adminCourseDetail: (courseId: string) => `/admin/courses/${courseId}`,
  adminCourseEdit: (courseId: string) => `/admin/courses/${courseId}/edit`,
  adminCourseCreate: '/admin/courses/create',
  adminQuestions: '/admin/questions',
  adminQuestionDetail: (questionId: string) => `/admin/questions/${questionId}`,
  adminQuestionEdit: (questionId: string) => `/admin/questions/${questionId}/edit`,
  adminQuestionCreate: '/admin/questions/create',
  adminCollections: '/admin/collections',
  adminCollectionDetail: (collectionId: string) => `/admin/collections/${collectionId}`,
  adminCollectionEdit: (collectionId: string) => `/admin/collections/${collectionId}/edit`,
  adminCollectionCreate: '/admin/collections/create',
  adminTests: '/admin/tests',
  adminTestDetail: (testId: string) => `/admin/tests/${testId}`,
  adminTestEdit: (testId: string) => `/admin/tests/${testId}/edit`,
  adminTestCreate: '/admin/tests/create',
  adminUsers: '/admin/users',
  adminUserEdit: (userId: string) => `/admin/users/${userId}/edit`,
  testSessions: '/tests/sessions',
};
